Aux dev/register form new
Wolox/conduit-react pull request #14
Opened 2021-08-12 17:38 UTC by renzowolox

## Summary
* Register form
* Tests

## Screenshots
https://user-images.githubusercontent.com/53195970/129242902-9f697043-1b42-4480-842b-6c91e1679fe8.mov

## Trello card
https://trello.com/c/Vrx2U4cb/21-front-registration-form

2021-08-18 19:10 UTC, hernan-clich reviewed
I noticed a few things, it'd be great if you could take a look.

2021-08-18 19:10 UTC, hernan-clich commented on src/screens/Authentication/Login/index.tsx
> +        <Link to="/register" className={styles.linkToAccount}>
Please import the `PATHS` and try something like: `<Link to={PATHS.register} ...>` so if the route ever changes you only need to change it in one single place.

2021-08-18 19:10 UTC, hernan-clich commented on src/screens/Authentication/Register/index.tsx
> +        <Link to="/login" className={styles.linkToAccount}>
Same here, use `PATHS` constant

2021-08-19 19:28 UTC, renzowolox commented on src/components/FormInput/index.tsx
> +    (touched === undefined || touched) &&
I understand that yes, this component comes with bootstrap. And I just added the condition showErrorWithoutText.

2021-08-19 20:07 UTC, renzowolox commented on src/components/UserForm/index.tsx
> +/* eslint-disable complexity */
This comment shouldn't be here, I forgot to remove it.

2021-08-19 22:12 UTC, PipeWolox approved these changes

2021-08-19 22:36 UTC, PipeWolox requested changes

2021-08-19 22:36 UTC, PipeWolox commented on src/components/Routes/index.tsx
> +              ...user
You could just pass the user right?
`authActions.setUser(user)`

2021-08-19 22:36 UTC, PipeWolox commented on src/screens/Authentication/Login/index.tsx
> +              ...user
You could just pass the user right?

`authActions.setUser(user)`

2021-08-19 22:36 UTC, PipeWolox commented on src/screens/Authentication/Register/index.tsx
> +              ...user
equal to te previous

2021-08-20 14:28 UTC, hernan-clich reviewed
Once the comments from Pipe are resolved I'll give you my approval!

2021-08-20 17:44 UTC, PipeWolox approved these changes
Great!! Good Work!! 👍

2021-08-20 18:09 UTC, hernan-clich approved these changes
Nice job man! 💯

2021-08-23 13:11 UTC, merged